export * from './creatorRoles.service';
import { CreatorRolesService } from './creatorRoles.service';
export * from './creators.service';
import { CreatorsService } from './creators.service';
export * from './developers.service';
import { DevelopersService } from './developers.service';
export * from './games.service';
import { GamesService } from './games.service';
export * from './genres.service';
import { GenresService } from './genres.service';
export * from './platforms.service';
import { PlatformsService } from './platforms.service';
export * from './publishers.service';
import { PublishersService } from './publishers.service';
export * from './stores.service';
import { StoresService } from './stores.service';
export * from './tags.service';
import { TagsService } from './tags.service';
export const APIS = [CreatorRolesService, CreatorsService, DevelopersService, GamesService, GenresService, PlatformsService, PublishersService, StoresService, TagsService];
