/**
 * RAWG Video Games Database API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Developer } from './developer';


export interface DevelopersList200Response { 
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Developer>;
}

