/**
 * RAWG Video Games Database API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GamePlatformsInnerRequirements } from './gamePlatformsInnerRequirements';
import { GamePlatformsInnerPlatform } from './gamePlatformsInnerPlatform';


export interface GamePlatformsInner { 
    platform?: GamePlatformsInnerPlatform;
    released_at?: string | null;
    requirements?: GamePlatformsInnerRequirements | null;
}

