/**
 * RAWG Video Games Database API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GameEsrbRating { 
    id?: number;
    slug?: GameEsrbRating.SlugEnum;
    name?: GameEsrbRating.NameEnum;
}
export namespace GameEsrbRating {
    export const SlugEnum = {
        Everyone: 'everyone',
        Everyone10Plus: 'everyone-10-plus',
        Teen: 'teen',
        Mature: 'mature',
        AdultsOnly: 'adults-only',
        RatingPending: 'rating-pending'
    } as const;
    export type SlugEnum = typeof SlugEnum[keyof typeof SlugEnum];
    export const NameEnum = {
        Everyone: 'Everyone',
        Everyone10: 'Everyone 10+',
        Teen: 'Teen',
        Mature: 'Mature',
        AdultsOnly: 'Adults Only',
        RatingPending: 'Rating Pending'
    } as const;
    export type NameEnum = typeof NameEnum[keyof typeof NameEnum];
}


