/**
 * RAWG Video Games Database API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GameStoreFull { 
    readonly id?: number;
    readonly game_id?: string;
    readonly store_id?: string;
    url: string;
}

