/**
 * RAWG Video Games Database API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonSingle { 
    readonly id?: number;
    name: string;
    readonly slug?: string;
    readonly image?: string;
    readonly image_background?: string;
    description?: string;
    readonly games_count?: number;
    readonly reviews_count?: number;
    readonly rating?: string;
    readonly rating_top?: number;
    readonly updated?: string;
}

