/**
 * RAWG Video Games Database API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Reddit { 
    readonly id?: number;
    readonly name?: string;
    readonly text?: string;
    readonly image?: string;
    readonly url?: string;
    readonly username?: string;
    readonly username_url?: string;
    readonly created?: string;
}

