/**
 * RAWG Video Games Database API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScreenShot { 
    readonly id?: number;
    /**
     * An image file with size up to 20 MB.
     */
    readonly image?: string;
    /**
     * Set image as hidden or visible.
     */
    hidden?: boolean;
    readonly width?: number;
    readonly height?: number;
}

