/**
 * RAWG Video Games Database API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Twitch { 
    readonly id?: number;
    readonly external_id?: number;
    readonly name?: string;
    readonly description?: string;
    readonly created?: string;
    readonly published?: string;
    readonly thumbnail?: string;
    readonly view_count?: number;
    readonly language?: string;
}

