/**
 * RAWG Video Games Database API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Youtube { 
    readonly id?: number;
    readonly external_id?: string;
    readonly channel_id?: string;
    readonly channel_title?: string;
    readonly name?: string;
    readonly description?: string;
    readonly created?: string;
    readonly view_count?: number;
    readonly comments_count?: number;
    readonly like_count?: number;
    readonly dislike_count?: number;
    readonly favorite_count?: number;
    readonly thumbnails?: object;
}

